# Set prefix to backtick
unbind C-b
set-option -g prefix `
bind-key ` send-prefix

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g focus-events on

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Allow terminal notifications pass-through to outer terminal
set -g allow-passthrough on

